/**
 * Docs search controller — everything about searching, nothing about the DOM.
 *
 * The view layer subscribes to `SearchState` and renders it. Keeping selection
 * (which result is highlighted) out of here is deliberate: that is view state,
 * and it belongs to whatever renders the list.
 */

/** The slice of Pagefind's JS API this controller uses. */
export interface PagefindModule {
  init(): Promise<void>;
  search(term: string): Promise<{
    results: { data(): Promise<PagefindResultData> }[];
  }>;
}

interface PagefindResultData {
  url: string;
  excerpt: string;
  meta?: { title?: string };
}

export interface SearchResult {
  url: string;
  title: string;
  /** Pagefind excerpt HTML; contains <mark> around matched terms. */
  excerpt: string;
}

export type SearchState =
  | { kind: 'idle' }
  | { kind: 'results'; results: SearchResult[] }
  | { kind: 'empty'; term: string }
  | { kind: 'unavailable' };

export interface SearchController {
  /** Debounced. Later calls invalidate earlier in-flight ones. */
  query(term: string): void;
  /** Returns an unsubscribe function. Fires immediately with current state. */
  subscribe(listener: (state: SearchState) => void): () => void;
  /** Warm the index, e.g. when the dialog opens. Never rejects. */
  preload(): Promise<void>;
  /** Drop any pending debounce and return to idle. */
  reset(): void;
}

export interface SearchControllerOptions {
  /**
   * Injected for tests. Defaults to loading Pagefind's generated bundle, which
   * only exists in production build output — see the `build` script.
   */
  loadPagefind?: () => Promise<PagefindModule>;
  debounceMs?: number;
  limit?: number;
}

function defaultLoadPagefind(): Promise<PagefindModule> {
  // Held in a variable so Vite treats it as fully dynamic. The path is
  // generated by the Pagefind CLI after `astro build`, so it cannot be
  // resolved at bundle time.
  const bundle = '/pagefind/pagefind.js';
  return import(/* @vite-ignore */ bundle) as Promise<PagefindModule>;
}

export function createSearchController(
  options: SearchControllerOptions = {},
): SearchController {
  const {
    loadPagefind = defaultLoadPagefind,
    debounceMs = 140,
    limit = 8,
  } = options;

  const listeners = new Set<(state: SearchState) => void>();
  let state: SearchState = { kind: 'idle' };
  let debounceTimer: ReturnType<typeof setTimeout> | undefined;

  /**
   * Monotonic query token. Every async continuation re-checks it, so a slow
   * earlier response can never overwrite a newer one.
   */
  let token = 0;

  /** Resolves once, then memoized — including the failure, so a missing index
   * does not re-attempt the import on every keystroke. */
  let pagefind: Promise<PagefindModule | null> | undefined;

  function emit(next: SearchState): void {
    state = next;
    for (const listener of listeners) listener(state);
  }

  function ensurePagefind(): Promise<PagefindModule | null> {
    pagefind ??= loadPagefind()
      .then(async module => {
        await module.init();
        return module;
      })
      .catch(() => null);
    return pagefind;
  }

  async function run(term: string, requested: number): Promise<void> {
    const api = await ensurePagefind();
    if (requested !== token) return;

    if (!api) {
      emit({ kind: 'unavailable' });
      return;
    }

    const search = await api.search(term);
    if (requested !== token) return;

    const results = await Promise.all(
      search.results.slice(0, limit).map(result => result.data()),
    );
    if (requested !== token) return;

    if (results.length === 0) {
      emit({ kind: 'empty', term });
      return;
    }

    emit({
      kind: 'results',
      results: results.map(result => ({
        url: result.url,
        title: result.meta?.title || result.url,
        excerpt: result.excerpt,
      })),
    });
  }

  return {
    query(term) {
      clearTimeout(debounceTimer);
      // Bump the token even for an empty term, so an in-flight query for the
      // previous term cannot land after the user has cleared the box.
      token += 1;

      if (term.trim() === '') {
        emit({ kind: 'idle' });
        return;
      }

      const requested = token;
      debounceTimer = setTimeout(() => {
        void run(term, requested);
      }, debounceMs);
    },

    subscribe(listener) {
      listeners.add(listener);
      listener(state);
      return () => {
        listeners.delete(listener);
      };
    },

    async preload() {
      await ensurePagefind();
    },

    reset() {
      clearTimeout(debounceTimer);
      token += 1;
      emit({ kind: 'idle' });
    },
  };
}
