<script lang="ts">
  // Docs search dialog. Searching lives in scripts/search-controller.ts, which
  // has no DOM knowledge and is unit-tested separately; this owns presentation
  // and selection only.
  //
  // Native <dialog> + showModal() is deliberate: it provides the focus trap,
  // Esc handling, background inertness, and top-layer rendering. Top layer
  // matters because the header is sticky with a backdrop-filter that would
  // otherwise capture a positioned overlay. None of that is reimplemented here.
  import { onMount } from 'svelte';
  import {
    createSearchController,
    type PagefindModule,
    type SearchState,
  } from '../scripts/search-controller.js';
  import { SEARCH_OPEN_EVENT } from '../scripts/search-events.js';

  const IDLE_MESSAGE = 'Type to search the documentation.';
  const UNAVAILABLE_MESSAGE =
    'Search index unavailable. It is generated by the production build (pnpm --filter @shipbench/site build).';

  // Injected only by tests. Production renders this with no props and gets the
  // controller's default loader, which reads the built Pagefind bundle.
  const { loadPagefind }: { loadPagefind?: () => Promise<PagefindModule> } =
    $props();

  // svelte-ignore state_referenced_locally
  // Read once on purpose: the controller is created once, and this prop is a
  // fixed test seam that never changes after mount.
  const controller = createSearchController(
    loadPagefind ? { loadPagefind } : {},
  );

  let dialog: HTMLDialogElement;
  let input = $state<HTMLInputElement | undefined>();
  let list = $state<HTMLUListElement | undefined>();

  let searchState = $state<SearchState>({ kind: 'idle' });
  /** Selection is view state, which is why it never entered the controller. */
  let activeIndex = $state(0);

  const results = $derived(
    searchState.kind === 'results' ? searchState.results : [],
  );
  const status = $derived(
    searchState.kind === 'results'
      ? ''
      : searchState.kind === 'empty'
        ? `No results for "${searchState.term}".`
        : searchState.kind === 'unavailable'
          ? UNAVAILABLE_MESSAGE
          : IDLE_MESSAGE,
  );

  onMount(() => {
    const unsubscribe = controller.subscribe(next => {
      searchState = next;
      // Any new result set starts at the top.
      activeIndex = 0;
    });
    document.addEventListener(SEARCH_OPEN_EVENT, open);
    return () => {
      unsubscribe();
      document.removeEventListener(SEARCH_OPEN_EVENT, open);
    };
  });

  export function open(): void {
    if (dialog.open) return;
    dialog.showModal();
    if (input) {
      input.value = '';
      input.focus();
    }
    // Clears anything left from a previous open, and re-renders into fresh
    // markup after a navigation.
    controller.reset();
    void controller.preload();
  }

  function move(delta: number): void {
    if (results.length === 0) return;
    // Wrap around — a result list is a loop, not a dead end at either edge.
    activeIndex = (activeIndex + delta + results.length) % results.length;
    list
      ?.querySelector(`#search-result-${activeIndex}`)
      ?.scrollIntoView({ block: 'nearest' });
  }

  function openActive(): void {
    const url = results[activeIndex]?.url;
    if (url) window.location.href = url;
  }

  function onKeydown(event: KeyboardEvent): void {
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      move(1);
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      move(-1);
    } else if (event.key === 'Enter') {
      // The form is method="dialog"; Enter would otherwise just close it.
      event.preventDefault();
      openActive();
    }
  }

  function onDialogClick(event: MouseEvent): void {
    // showModal() stretches the dialog's own box over the viewport for
    // centering, so a backdrop click lands on the dialog itself.
    if (event.target === dialog) dialog.close();
  }
</script>

<dialog
  bind:this={dialog}
  id="search-modal"
  class="search-modal"
  aria-label="Search documentation"
  onkeydown={onKeydown}
  onclick={onDialogClick}
>
  <form method="dialog" class="search-modal-form">
    <div class="search-field">
      <svg class="search-field-icon" width="14" height="14" viewBox="0 0 16 16" aria-hidden="true">
        <circle cx="7" cy="7" r="4.5" fill="none" stroke="currentColor" stroke-width="1.5" />
        <path d="M10.5 10.5 L14 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
      </svg>
      <input
        bind:this={input}
        id="search-input"
        class="search-input"
        type="search"
        role="combobox"
        placeholder="Search docs..."
        aria-label="Search documentation"
        aria-controls="search-results"
        aria-expanded={results.length > 0}
        aria-activedescendant={results.length > 0 ? `search-result-${activeIndex}` : undefined}
        aria-autocomplete="list"
        autocomplete="off"
        spellcheck="false"
        oninput={event => controller.query(event.currentTarget.value)}
      />
      <button class="search-close" type="submit" aria-label="Close search">Esc</button>
    </div>

    <div class="search-body">
      {#if status}
        <p id="search-status" class="search-status" role="status" aria-live="polite">
          {status}
        </p>
      {/if}
      <ul
        bind:this={list}
        id="search-results"
        class="search-results"
        role="listbox"
        aria-label="Search results"
      >
        {#each results as result, i (result.url)}
          <!-- svelte-ignore a11y_click_events_have_key_events -->
          <!-- Keyboard access is the combobox's job: the input keeps focus and
               drives selection through aria-activedescendant, so options are
               deliberately not individually focusable. -->
          <li
            id="search-result-{i}"
            class="search-result"
            class:active={i === activeIndex}
            role="option"
            aria-selected={i === activeIndex}
            onclick={() => {
              window.location.href = result.url;
            }}
          >
            <span class="search-result-title">{result.title}</span>
            <!-- Pagefind marks matched terms with <mark> in the excerpt. -->
            <!-- eslint-disable-next-line svelte/no-at-html-tags -->
            <span class="search-result-excerpt">{@html result.excerpt}</span>
          </li>
        {/each}
      </ul>
    </div>

    <div class="search-foot">
      <span><kbd>↑</kbd><kbd>↓</kbd> navigate</span>
      <span><kbd>↵</kbd> open</span>
      <span><kbd>Esc</kbd> close</span>
    </div>
  </form>
</dialog>
